name: CI - Build wxPython

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build wxPython
    runs-on: macos-latest

    env:
      branch: ${{ github.ref }}
      commiturl: ${{ github.event.head_commit.url }}${{ github.event.release.html_url }}
      commitdate: ${{ github.event.head_commit.timestamp }}${{ github.event.release.published_at }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Force Universal2 charset for Python
        run: |
          python3 -m pip uninstall -y charset_normalizer
          python3 -m pip download --platform macosx_10_9_universal2 --only-binary=:all: charset-normalizer
          python3 -m pip install charset_normalizer-*-macosx_10_9_universal2.whl

      - name: Prepare Assets (--prepare-assets)
        run: >
          python3 Build-Project.command
          --run-as-individual-steps --reset-dmg-cache
          --prepare-assets

      - name: Prepare Application (--prepare-application)
        run: >
          python3 Build-Project.command
          --git-branch "${{ env.branch }}"
          --git-commit-url "${{ env.commiturl }}"
          --git-commit-date "${{ env.commitdate }}"
          --reset-pyinstaller-cache
          --run-as-individual-steps
          --prepare-application

      - name: Prepare Package (--prepare-package)
        run: >
          python3 Build-Project.command
          --run-as-individual-steps
          --prepare-package

      - name: Upload AutoPkg Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AutoPkg-Assets.pkg
          path: ./dist/AutoPkg-Assets.pkg

      - name: Upload Installation Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher.pkg
          path: ./dist/OpenCore-Patcher.pkg

      - name: Upload Uninstaller Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher-Uninstaller.pkg
          path: ./dist/OpenCore-Patcher-Uninstaller.pkg

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/AutoPkg-Assets.pkg
            ./dist/OpenCore-Patcher.pkg
            ./dist/OpenCore-Patcher-Uninstaller.pkg
          generate_release_notes: false
          body: |
            ## OpenCore Legacy Patcher ${{ github.ref_name }}

            ### Changes
            - Added T2 Mac support for MacBookAir8,1 (MacBook Air 2018) and MacBookAir8,2 (MacBook Air 2019)
            - Fixes kernel panic: `AppleSEPManager panic for AppleKeyStore: sks request timeout`
