name: CI - Validation (External)

on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-13
    if: github.repository_owner != 'dortania'

    steps:
      - uses: actions/checkout@v4

      - name: Install Universal Python 3.14
        run: |
          curl -fsSL -o python-installer.pkg https://www.python.org/ftp/python/3.14.0/python-3.14.0-macos11.pkg
          sudo installer -pkg python-installer.pkg -target /
          echo "/Library/Frameworks/Python.framework/Versions/3.14/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 -m pip install -r requirements.txt

      - name: Validate
        run: /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 OpenCore-Patcher-GUI.command --validate
